# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Author:: Ken-ichi TANABE (<nabeken@tknetworks.org>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Vagrant.configure("2") do |config|
  config.vm.guest = :openbsd
  config.vm.box = "vagrant-openbsd-54c-20130819"
  config.vm.box_url = "http://projects.tsuntsun.net/~nabeken/boxes/vagrant-openbsd-54c-20130819.box"
  config.vm.hostname = "packer-fuguita.dev"
  config.vm.network :private_network, ip: "192.168.50.10"
  config.vm.synced_folder "../", "/vagrant", :disabled => true
  config.vm.provision :shell, :inline => '/etc/rc.d/httpd -f start'
  config.vm.provision :shell, :inline => %Q{
  cat <<_EOF_ > /var/www/htdocs/install.conf
system hostname = build-fuguita.dev
network interfaces = em0
IPv4 address for em0? = dhcp
Password for root account? = password
Password for vagrant account? = vagrant
Since you set up a user, disable sshd(8) logins to root? = no
Location of sets? = http
What timezone are you in? = Asia/Tokyo
Server? = ftp.iij.ad.jp
Do you expect to run the X Window System? = no
Setup a user? = vagrant
Public ssh key for vagrant = ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
Set name(s)? = -x* -game*
_EOF_
  }
end
