--- Makefile.orig	Sat Nov  3 15:06:38 2012
+++ Makefile	Sat Nov  3 15:07:18 2012
@@ -1,6 +1,6 @@
 #	$OpenBSD: Makefile,v 1.4 2007/10/18 18:16:20 deraadt Exp $
 
-SUBDIR= ramdisk_cd ramdiskA cdfs
+SUBDIR= ramdisk_cd ramdiskA cdfs fuguita_cd fuguita-cdfs
 
 .if	make(obj) || make(cleandir) || make(clean)
 SUBDIR+= iso
@@ -9,5 +9,6 @@
 unconfig:
 	cd ramdisk_cd; ${MAKE} unconfig
 	cd ramdiskA; ${MAKE} unconfig
+	cd fuguita_cd; ${MAKE} unconfig
 
 .include <bsd.subdir.mk>
